// Explicitly reviewed mappings; question snapshots never depend on this registry.
export const registryVersion = 'docs-2026-09-09-v3';
const rows = [
  [
    'lab-tags',
    'Apply resource tags with Azure CLI',
    'identity.governance',
    ['tags'],
    'azure/azure-resource-manager/management/tag-resources-cli',
  ],
  [
    'lab-vnet',
    'Create and manage a virtual network',
    'networking.networks',
    ['create'],
    'azure/virtual-network/manage-virtual-network',
  ],
  [
    'users',
    'Create Microsoft Entra users',
    'identity.users',
    ['create'],
    'entra/identity/users/users-bulk-add',
    'entra-docs',
  ],
  [
    'rbac',
    'Azure role-based access control',
    'identity.access',
    ['assignments', 'interpret'],
    'azure/role-based-access-control/overview',
  ],
  [
    'governance',
    'Management groups',
    'identity.governance',
    ['management-groups'],
    'azure/governance/management-groups/overview',
  ],
  [
    'sas',
    'Shared access signatures',
    'storage.access',
    ['sas', 'policies'],
    'azure/storage/common/storage-sas-overview',
  ],
  [
    'redundancy',
    'Storage redundancy',
    'storage.accounts',
    ['redundancy'],
    'azure/storage/common/storage-redundancy',
  ],
  [
    'lifecycle',
    'Blob lifecycle management',
    'storage.data',
    ['lifecycle'],
    'azure/storage/blobs/lifecycle-management-overview',
  ],
  [
    'bicep',
    'Create Bicep files with Visual Studio Code',
    'compute.templates',
    ['bicep'],
    'azure/azure-resource-manager/bicep/quickstart-create-bicep-use-visual-studio-code',
  ],
  [
    'vms',
    'Virtual machine availability',
    'compute.vms',
    ['availability'],
    'azure/virtual-machines/availability',
    'azure-compute-docs',
  ],
  [
    'containers',
    'Azure Container Instances',
    'compute.containers',
    ['instances'],
    'azure/container-instances/container-instances-overview',
    'azure-compute-docs',
  ],
  [
    'apps',
    'App Service deployment slots',
    'compute.apps',
    ['slots'],
    'azure/app-service/deploy-staging-slots',
  ],
  [
    'routes',
    'Virtual network routing',
    'networking.networks',
    ['routes'],
    'azure/virtual-network/virtual-networks-udr-overview',
  ],
  [
    'nsg',
    'Network security groups',
    'networking.security',
    ['groups'],
    'azure/virtual-network/network-security-groups-overview',
  ],
  [
    'dns',
    'Private DNS virtual network links',
    'networking.dns',
    ['dns'],
    'azure/dns/private-dns-virtual-network-links',
  ],
  [
    'balancer',
    'Azure Load Balancer',
    'networking.dns',
    ['balancer'],
    'azure/load-balancer/load-balancer-overview',
  ],
  [
    'metric-alerts',
    'Create metric alert rules',
    'monitoring.monitor',
    ['alerts'],
    'azure/azure-monitor/alerts/alerts-create-metric-alert-rule',
    'azure-monitor-docs',
  ],
  [
    'queries',
    'Get started with log queries',
    'monitoring.monitor',
    ['queries'],
    'azure/azure-monitor/logs/get-started-queries',
    'azure-monitor-docs',
  ],
  [
    'backup',
    'Azure Files backup',
    'monitoring.backup',
    ['restore'],
    'azure/backup/azure-file-share-backup-overview',
  ],
];
export const documents = rows.map(
  ([id, title, objectiveId, skillNames, path, repository = 'azure-docs']) => ({
    id,
    title,
    objectiveId,
    domainId: objectiveId.split('.')[0],
    skillIds: skillNames.map((name) => `${objectiveId}.${name}`),
    url: `https://learn.microsoft.com/en-us/${path}`,
    repository,
    license: repository === 'entra-docs' ? 'MIT' : 'CC BY 4.0',
    licenseUrl: `https://github.com/MicrosoftDocs/${repository}/blob/main/LICENSE`,
    attribution: '© Microsoft Corporation and contributors',
    codeLicense: 'MIT',
    codeLicenseUrl: `https://github.com/MicrosoftDocs/${repository}/blob/main/${repository === 'entra-docs' ? 'LICENSE' : 'LICENSE-CODE'}`,
    changes: 'Article content extracted for reading; site chrome and executable media removed.',
    reviewedAt: ['lab-tags', 'lab-vnet'].includes(id) ? '2026-09-09' : '2026-09-06',
    registryVersion,
  }),
);
// Anchors are source anchors, not mutable question properties.
export const sectionMappings = {
  'monitoring.monitor.alerts': ['metric-alerts', 'configure-conditions'],
  'identity.access.assignments': ['rbac', 'role-assignments'],
  'identity.access.interpret': [
    'rbac',
    'how-azure-rbac-determines-if-a-user-has-access-to-a-resource',
  ],
};
